"""add_image_url_to_ads

Revision ID: 1d54f780f90f
Revises: 246a0cedc0a6
Create Date: 2026-03-08 21:57:23.972812
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d54f780f90f'
down_revision: Union[str, None] = '246a0cedc0a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('image_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'image_url')
    # ### end Alembic commands ###
